debian/elementary-default-settings.gsettings-override
We wanna use 4500 as our default, as reflected in https://github.com/elementary/switchboard-plug-display/pull/72 and https://github.com/elementary/wingpanel-indicator-nightlight/pull/8
=> Set default Night Light settings

appcenter.blacklist
Fixes #54 
* Updates IDs for those that have dropped `.desktop`
* Remove IDs that just don't exist anymore
* Add budgie desktop stuff and more packages that only work on other desktops
=> Update appcenter blacklist for Juno

debian/elementary-default-settings.gsettings-override
Make sure we don't change the default appearance with https://github.com/elementary/wingpanel-indicator-datetime/pull/81
=> Set clock-show-date to true

overrides/default-settings.gschema.override
Out of the box, Ephemeral and Brave both block third-party cookies to reduce unwanted forms of cross-site tracking via ads. It'd be great for elementary's default browser to ship a privacy enhancing default. Fixes #127.
The same setting has been working well for me in Firefox (my default browser) since over a year, without any noticeable regression. In my limited testing, as far as I can tell, Epiphany is working fine with some popular sites.
=>  Accept only first party cookies for enhanced privacy

accountsservice/io.elementary.pantheon.AccountsService.xml
These are the required keys for the power settings plug to be able to set power settings readable by the greeter.
=> Add AccountsService interfaces for greeter power settings

overrides/default-settings.gschema.override
gsettings-desktop-schemas removed this key a long time ago [0].
It appears ubuntu has reverted this for some reason, though it's
completely ignored and deprecated. Having this in the overrride
should be needless because ubuntu has the setting on by default.
[0]: https://gitlab.gnome.org/GNOME/gsettings-desktop-schemas/commit/a59b45e766a2b3732b3bd2473ee5fbe7607a7f75
=> Don't set draw-background

overrides/default-settings.gschema.override
This was introduced to workaround a bug where cursors would be invisible 
with g-s-d. The report [0] was never actually closed, and I haven't noti-
ced any one's recently. I believe the issue is now gone in recent versions.
(reports mentioned gtk 3.10) The was also interfering with cursor-size settings.
Fixes https://github.com/elementary/gala/issues/300
[0]: https://bugzilla.gnome.org/show_bug.cgi?id=694758
=> Don't Inactivate g-s-d cursor plugin

overrides/default-settings.gschema.override
We changed this a long time ago because search results weren't very good. However, I think at this time the results for DuckDuckGo have improved a lot and it would be good to consider this switch again
=> Make default search engine DuckDuckGo

overrides/default-settings.gschema.override
Fixes #143
0 = Do not show (default)
1 = Auto hide
2 = Always show
=> Automatically show & hide the property panel of IBus

profile.d/pantheon-filechooser-module.sh
The docs on GTK_MODULES states this
> Note that this environment variable is read by GTK+ 2.x too, which may not have the same set of modules available for loading. Use GTK3_MODULES for modules that are only compatible with GTK+ 3. 
and this module is only compatible with GTK 3, so we should be using `GTK3_MODULES`.
This typically produces some benign warnings in the outputs like:
Gtk-WARNING **: 13:33:12.201: GTK+ module /run/current-system/sw/lib/gtk-3.0/modules/libpantheon-filechooser-module.so cannot be loaded.
GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported.
Gtk-Message: 13:33:12.202: Failed to load module "pantheon-filechooser-module"
We also use safer parameter expansions, see https://wiki-dev.bash-hackers.org/syntax/pe#use_an_alternate_valu …
=> profile.d: use GTK3_MODULES over GTK_MODULES

overrides/default-settings.gschema.override
I highly doubt this actually does anything anymore
=> default-settings.gschema.override: Remove old show-desktop-icons

overrides/default-settings.gschema.override
These need to go in an array now and it seems `<Super>l` is already the default screensaver shortcut
=> focal: fix media keys syntax

accountsservice/io.elementary.pantheon.AccountsService.xml
From https://dbus.freedesktop.org/doc/dbus-api-design.html:
>In particular, sending structured strings over D-Bus should be avoided, as they need to be built and parsed; both are complex operations which are prone to bugs.
>For APIs being used in constrained situations, enumerated values should be transmitted as unsigned integers.
It sounds like it is expected to be implemented as an enum on the client side and then just send the int over DBus. In this case we would use:
- `0` no preference
- `1` prefer dark
- `2` prefer light
=> AccountsService: Change PrefersColorScheme to enum

overrides/default-settings.gschema.override.in
lfg for 6.0. Also removes a deprecated and unused key. I know we've talked about potentially not overriding the system GTK stylesheet, but I'm not sure if/how we'll end up addressing that. This at least sets the new stylesheet instead of the old one for dailies.
=> Overrides: use greenfield stylesheet by default

overrides/default-settings.gschema.override.in
This would have been disabled to stop it interfering with light-locker as much I guess. But since we now intend to use this key to enable/disable our Gala screen locker when the session goes idle, we should let it revert back to the GNOME default of true.
=> Enable screensaver locking by default

accountsservice/io.elementary.pantheon.AccountsService.xml
Adds two keys to mirror the keys in `org.gnome.desktop.input-sources` so that we can synchronise keyboard layouts between user sessions and the greeter.
These will also be useful for initial setup to initially set the keyboard layout on a new user once created.
=> accountsservice: Add keys for keyboard layout

overrides/default-settings.gschema.override.in
This is the key that controls how long the session can be idle for before the screen is blanked. This was previously controlled by DPMS helper and the default was 15 minutes, so this allows us to have the same default.
=> Set default idle delay to 15 minutes

skel/plank/dock1/launchers/org.gnome.Epiphany.dockitem
Gets Epiphany back into the dock.
=> org.gnome.Epiphany.dockitem: Point to Flatpak

accountsservice/io.elementary.pantheon.AccountsService.xml
Will fix #175. Open to feedback.
My reason for having `0` equal "No Preference" while also having blue is because it seemed the most flexible if we wanted to change how the accent color stuff worked down the line, without hardcoding the default to blue. But maybe this is overthinking it.
=> AccountsService: Add PrefersAccentColor to users

profile.d/gtk-filechooser-native.sh
As defined in https://gitlab.gnome.org/GNOME/gtk/-/blob/master/gdk/gdk.c#L384
=> Force the use of the portal by default for native GTK widgets

debian/control
Possibly fixes: https://github.com/elementary/os/issues/432 and/or https://github.com/elementary/appcenter/issues/1470
This seems like some weird historical crap from before we had seeds https://github.com/elementary/default-settings/commit/3b8d347a0fbe240904f394b57ef9c367b072c3c0
=> Control: remove recommends covered by seeds

debian/elementary-default-settings.maintscript
Even though we've now removed these config files from the package, dpkg won't automatically remove them when newer versions of the package are installed because it doesn't remove config.
This change causes them to be deleted (unless the user has modified them) if the new version of the package being installed <= 6.0.0, so it'll work with the stable release of the package in the future too.
=> Remove old profile shell scripts on upgrade

overrides/default-settings.gschema.override.in
We missed this, and it fixes launching the applications menu with a keyboard shortcut. Why are we doing this here, anyway??
=> GSettings override: Use WingPanel RDNN for Gala

debian/elementary-default-settings.maintscript, profile.d/pantheon-filechooser-module.sh
We no longer have this module in 6.0. We should stop pushing it into the environment variables as it causes a warning about it being missing every time you start a GTK app from the terminal.
=> Remove pantheon-filechooser-module.sh

accountsservice/io.elementary.pantheon.AccountsService.xml
Unless we want to ship grape by default, no preference isn't the correct default here. This makes blueberry the default.
=> PrefersAccentColor: default to blue

skel/plank/dock1/launchers/io.elementary.mail.dockitem
Fixes Mail not showing in the dock on latest daily images
=> Mail dockitem: Update to Flatpak path

skel/plank/dock1/launchers/io.elementary.mail.dockitem
This reverts commit e48798b5ab0818f019702860df0535cb79a109aa due to https://github.com/elementary/os/pull/496 and https://github.com/elementary/seeds/pull/77
=> Revert "Mail dockitem: Update to Flatpak path (#234)"

overrides/default-settings.gschema.override.in
This never worked, plus it's RDNN under `io.elementary.notifications` now anyway.
=> GSchema: Remove nonfunctional notifications override

overrides/default-settings.gschema.override.in
Depends on https://github.com/elementary/dock/pull/108. Retains the dockitem override in its separate file.
=> GSchema: Remove Plank settings overrides

overrides/default-settings.gschema.override.in
Fixes #259 
Fixes #258 
Fixes #260
This MR migrates font settings to their new schema.
It also move the `show-unicode-menu` in the deprecated area.
Finally, it removes now useless Epiphany settings, which are either replaced by something else (cookie setting) and in both case activated by default.
=> Fix warnings introduced by Gnome 40+ and last versions of Epiphany

skel/plank/dock1/launchers/io.elementary.music.dockitem
Fixes missing Music from the Dock in OS 7
=> Music Dockitem: Point to var/lib/flatpak

debian/control, debian/elementary-printer-test-page.postrm, debian/elementary-printer-test-page.preinst
We shouldn't really be replacing the `cups-filters` package with a single PDF as it has a bunch more useful stuff than just the test page.
Additionally, this `cups-filters` package has now been renamed, so I'm now ending up with installation failures on `mantic` due to two packages trying to install the test page. So we should do this properly and just divert the one file we want to replace.
=> deb-packaging: Divert printer test page instead of replacing whole package

meson_options.txt
We don't have a dark wallpaper currently, and don't support changing it in switchboard either. As such we shouldn't set a dark wallpaper uri as the default, as it makes gala change the user selected wallpaper to the elementary default one.
=> Do Not Set a Default Dark Wallpaper

debian/install, gtk/settings.ini, meson.build
All these settings seem to be covered in dconf overrides and this file is conflicting with the file provided by libgtk-3-0t64
=> Remove Gtk settings.ini

debian/control, meson.build, profile.d/qt-qpa-platformtheme.sh, profile.d/qt-style-override.sh
Fixes #286 
Fixes #298 
Closes #304
=> Drop Qt style overrides

debian/install, meson_options.txt, overrides/meson.build, overrides/plank-dockitems.gschema.override, skel/meson.build, skel/plank/dock1/launchers/gala-multitaskingview.dockitem, skel/plank/dock1/launchers/io.elementary.appcenter.dockitem, skel/plank/dock1/launchers/io.elementary.calendar.dockitem, skel/plank/dock1/launchers/io.elementary.files.dockitem, skel/plank/dock1/launchers/io.elementary.mail.dockitem, skel/plank/dock1/launchers/io.elementary.music.dockitem, skel/plank/dock1/launchers/io.elementary.photos.dockitem, skel/plank/dock1/launchers/io.elementary.switchboard.dockitem, skel/plank/dock1/launchers/io.elementary.tasks.dockitem, skel/plank/dock1/launchers/io.elementary.videos.dockitem, skel/plank/dock1/launchers/org.gnome.Epiphany.dockitem
Turns out we want to keep Plank for the X11 session
=> Revert Plank removal

geoclue/beacondb.conf, geoclue/meson.build, meson.build
Fixes https://github.com/elementary/triage/issues/702
Adds a conf file for https://beacondb.net/ so we can get wifi location with GeoClue again
Identify user agent manually as requested at https://codeberg.org/beacondb/beacondb/issues/5#issuecomment-2504311
=> Add beacondb for GeoClue

geoclue/meson.build, meson_options.txt
Make geoclue conf optional since some distros ship their own
=> Meson: make geoclue conf optional
