elementary/default-settings

- debian/elementary-default-settings.gsettings-override
> Sort directories first in GTK FileChooser

- profile.d/pantheon-filechooser-module.sh
Just in case there are other modules.
> Append pantheon-filechooser-module to $GTK_MODULES

- debian/elementary-default-settings.gsettings-override
This gsettings path is now BS and we can just make these changes upstream
> Remove Scratch settings

- debian/elementary-default-settings.gsettings-override
I think we've done this in a patch before, but if it makes sense, we can just set it here.
> Add Epiphany tab override

- debian/elementary-default-settings.gsettings-override
- plank/dock1/launchers/io.elementary.videos.dockitem
- plank/dock1/launchers/org.pantheon.audience.dockitem
Fix Videos after the RDNN branch that just landed
> Rename audience to Videos

- debian/elementary-default-settings.gsettings-override
> Set super as the Overlay key

- debian/elementary-default-settings.gsettings-override
Depends on https://github.com/elementary/seed-metapackages/pull/7
> Change sound theme to elementary

- debian/elementary-default-settings.gsettings-override
> Set overlay key action as shortcut overlay by default

- debian/elementary-default-settings.gsettings-override
> Set default Epiphany search engine

- debian/elementary-default-settings.gsettings-override
- plank/dock1/launchers/io.elementary.photos.dockitem
- plank/dock1/launchers/org.pantheon.photos.dockitem
Fix .desktop names for photos and music
> Fix RDNN launcher names

- debian/elementary-default-settings.gsettings-override
- plank/dock1/launchers/io.elementary.switchboard.dockitem
- plank/dock1/launchers/org.pantheon.switchboard.dockitem
Also fix epiphany while we're here
> Update switchboard launcher for plank

- debian/elementary-default-settings.gsettings-override
Changing the case here was wrong, these are still uppercase
> Fix epiphany keys

- profile.d/qt-style-override.sh
> set Qt5 port of Adwaita theme

- overrides/default-settings.gschema.override
Opening this for discussion.
I know we disabled it previously because it was really aggressive and finicky, but I think it's worth re-evaluating to see if support has improved
> Enabled ambient light dimming

- overrides/default-settings.gschema.override
Neither of these have any effect anymore
> default-settings.gschema.override: removed unused interface keys

- overrides/default-settings.gschema.override
> Overrides: Set Inter 9 as default font

- accountsservice/io.elementary.pantheon.AccountsService.xml
Meant to match https://drafts.csswg.org/mediaqueries-5/#prefers-color-scheme
> AccountsService: Add a prefers color scheme key

- accountsservice/meson.build
> Add fallback accountsservice interfacesdir variable

- accountsservice/io.elementary.pantheon.AccountsService.xml
To match #167 and https://github.com/elementary/granite/pull/319
> AccountsService: PrefersColorScheme uint → int

- overrides/default-settings.gschema.override.in
> Enable Housekeeping by default

- overrides/plank-dockitems.gschema.override
This will revive the Mail icon in the dock on fresh install of Odin
> Update RDNN of Mail

- overrides/default-settings.gschema.override.in
Closes https://github.com/elementary/default-settings/issues/165
> Set default antialiasing to grayscale

- skel/plank/dock1/launchers/io.elementary.mail.dockitem
- skel/plank/dock1/launchers/org.pantheon.mail.dockitem
> Plank: Point to new Mail RDNN

- accountsservice/io.elementary.pantheon.AccountsService.xml
> PrefersAccentColor: Update No Preference comment for wallpaper-based accent

- skel/plank/dock1/launchers/io.elementary.tasks.dockitem
Fixes Tasks not showing on the dock in latest daily images
> Tasks dockitem: update to Flatpak path

- debian/install
> Install: Add flatpak repo to etc/skel

- skel/plank/dock1/launchers/io.elementary.tasks.dockitem
Probably needs https://github.com/elementary/seeds/pull/83
> Change Tasks launcher path to /usr/share

- debian/changelog
- meson.build
Doesn't look like there's any appdata here or anything and packaging is in tree
> Release 6.0.2

- overrides/plank-dockitems.gschema.override
- skel/plank/dock1/launchers/io.elementary.files.dockitem
> Plank: add Files dock item

- debian/changelog
- meson.build
> Release 7.0.0

- overrides/default-settings.gschema.override.in
> Overrides: set location services enabled by default

- debian/changelog
- meson.build
Guess there's no appdata for this project! Needed to allow using the location portal
> Release 7.0.2

- meson_options.txt
- overrides/default-settings.gschema.override.in
- overrides/meson.build
Also override the value for the default dark wallpaper
> Overrides: Set dark wallpaper

- meson.build
- xdg-desktop-portal/pantheon-portals.conf
Not really tested, closes: https://github.com/elementary/session-settings/issues/69.
> Add `pantheon-portals.conf`

- debian/control
Update Terminal's package name. Remove `enhances: plank`
> Control: update terminal package name, rm plank

- meson_options.txt
- overrides/meson.build
- overrides/plank-dockitems.gschema.override
- skel/meson.build
- skel/plank/dock1/launchers/gala-multitaskingview.dockitem
- skel/plank/dock1/launchers/io.elementary.appcenter.dockitem
- skel/plank/dock1/launchers/io.elementary.calendar.dockitem
- skel/plank/dock1/launchers/io.elementary.files.dockitem
- skel/plank/dock1/launchers/io.elementary.mail.dockitem
- skel/plank/dock1/launchers/io.elementary.music.dockitem
- skel/plank/dock1/launchers/io.elementary.photos.dockitem
- skel/plank/dock1/launchers/io.elementary.switchboard.dockitem
- skel/plank/dock1/launchers/io.elementary.tasks.dockitem
- skel/plank/dock1/launchers/io.elementary.videos.dockitem
- skel/plank/dock1/launchers/org.gnome.Epiphany.dockitem
Remove plank default launcher overrides
> Delete skel/plank directory

- debian/install
Our portals conf file isn't actually being installed
> Install: add pantheon-portals.conf

- meson_options.txt
- overrides/meson.build
- overrides/plank-dockitems.gschema.override
- skel/meson.build
- skel/plank/dock1/launchers/gala-multitaskingview.dockitem
- skel/plank/dock1/launchers/io.elementary.appcenter.dockitem
- skel/plank/dock1/launchers/io.elementary.calendar.dockitem
- skel/plank/dock1/launchers/io.elementary.files.dockitem
- skel/plank/dock1/launchers/io.elementary.mail.dockitem
- skel/plank/dock1/launchers/io.elementary.music.dockitem
- skel/plank/dock1/launchers/io.elementary.photos.dockitem
- skel/plank/dock1/launchers/io.elementary.settings.dockitem
- skel/plank/dock1/launchers/io.elementary.tasks.dockitem
- skel/plank/dock1/launchers/io.elementary.videos.dockitem
- skel/plank/dock1/launchers/org.gnome.Epiphany.dockitem
Once again remove plank overrides since we now have the new dock in X11 :sweat_smile:
> Remove Plank

- overrides/default-settings.gschema.override.in
https://github.com/elementary/gala/pull/2034
> Use new behavior schema

- meson.build
No metadata in this repo. Updates override for Gala schema
> Release 8.0.1

- overrides/default-settings.gschema.override.in
These are handled by settings daemon these days
> GSettings: don't set gnome privacy

- debian/install
- gtk/gtk4-settings.ini
- gtk/meson.build
- gtk/settings.ini
- meson.build
Fixes #318 
afaict apps that request SSD (like discord) are working properly with just this file and I'm not sure we need the gtk3 one
> Install gtk settings.ini

- overrides/default-settings.gschema.override.in
> Remove gala overrides

- .gitignore
- debian/control
- debian/postinst
Fixes https://github.com/elementary/appcenter/issues/2126
> Install brwap-userns-restrict apparmor profile

- overrides/default-settings.gschema.override.in
Follow up to https://github.com/elementary/gala/pull/2309
> Unset show-desktop shortcut

- apparmor/bwrap-userns-restrict
- meson.build
Fix several issues with Flatpak application (like GNOME Builder or Nextcloud)
> Add newer apparmor profile for bubblewrap

- debian/control
- debian/install
- debian/links
- debian/postinst
Depends on https://github.com/elementary/default-settings/pull/337
> Symlink using the patched apparmor profile

- apparmor/meson.build
- meson.build
- meson_options.txt
Since it doesn't apply to our Fedora friends etc
> Make AppArmor optional

- meson.build
Build on LP at the same time as https://github.com/elementary/gala/pull/2359
* New bubblewrap apparmor profile
* Adds beaconDB conf
* Unset show-desktop shortcut
> Release 8.1.0

- debian/install
> install: Add network configuration files

- overrides/default-settings.gschema.override.in
Fixes https://github.com/elementary/gala/issues/596
> Change toggle-maximized to Ctrl+Super+Up
